import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
import { Resend } from 'resend';
import dotenv from 'dotenv';
import cors from 'cors';
import { MongoClient, ObjectId, ServerApiVersion } from 'mongodb';
import fs from 'fs';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const resend = process.env.RESEND_API_KEY ? new Resend(process.env.RESEND_API_KEY) : null;
const ADMIN_EMAIL = process.env.ADMIN_EMAIL || 'ahmedchoudery30@gmail.com';
const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// Manual Asset Routing
app.get('/assets/:file', (req, res, next) => {
    const filePath = path.join(process.cwd(), 'dist', 'assets', req.params.file);
    if (fs.existsSync(filePath)) {
        if (req.params.file.endsWith('.js')) res.setHeader('Content-Type', 'application/javascript');
        if (req.params.file.endsWith('.css')) res.setHeader('Content-Type', 'text/css');
        // Assets with hashes can be cached!
        res.setHeader('Cache-Control', 'public, max-age=31536000, immutable');
        res.sendFile(filePath);
    } else { next(); }
});
// Static assets — disable default index serving to prevent cache interception
app.use(express.static(path.resolve(process.cwd(), 'dist'), { index: false }));

// MongoDB
let cachedDb = null;
async function connectDB() {
    if (cachedDb) return cachedDb;
    if (!process.env.MONGODB_URI) throw new Error('MONGODB_URI not defined');
    const client = new MongoClient(process.env.MONGODB_URI, {
        serverApi: { version: ServerApiVersion.v1, strict: true, deprecationErrors: true }
    });
    await client.connect();
    cachedDb = client.db('falak_hall_db');
    console.log('✅ Connected to MongoDB');
    return cachedDb;
}

// Admin auth middleware — checks x-admin-token header
function adminAuth(req, res, next) {
    const token = req.headers['x-admin-token'];
    if (!token || token !== process.env.ADMIN_TOKEN) {
        return res.status(401).json({ success: false, message: 'Unauthorized' });
    }
    next();
}

// ── PUBLIC API ─────────────────────────────────────────

app.post('/api/booking', async (req, res) => {
    try {
        const db = await connectDB();
        const { name, phone, email, eventDate, eventType, hall, guests, message } = req.body;
        if (!name || !phone || !eventDate || !eventType)
            return res.status(400).json({ success: false, message: 'Please fill in all required fields.' });
        const newBooking = {
            name, phone,
            email: email || '',
            eventDate, eventType,
            hall: hall || 'Any Available',
            guests: parseInt(guests) || 0,
            message: message || '',
            status: 'pending',
            source: 'online',
            createdAt: new Date(),
        };
        const result = await db.collection('bookings').insertOne(newBooking);


        // ── Admin Notification: Email via Resend ──
        if (resend) {
            try {
                await resend.emails.send({
                    from: 'Booking Alert <onboarding@resend.dev>',
                    to: [ADMIN_EMAIL],
                    subject: `New Booking: ${name} (${eventDate})`,
                    html: `
                        <div style="font-family: sans-serif; padding: 20px; border: 1px solid #C6A769; border-radius: 8px;">
                            <h2 style="color: #C6A769; border-bottom: 2px solid #C6A769; padding-bottom: 10px;">New Booking Inquiry</h2>
                            <p><strong>Customer:</strong> ${name}</p>
                            <p><strong>Phone:</strong> ${phone}</p>
                            <p><strong>Email:</strong> ${email || 'Not provided'}</p>
                            <p><strong>Event Date:</strong> ${eventDate}</p>
                            <p><strong>Event Type:</strong> ${eventType}</p>
                            <p><strong>Hall:</strong> ${hall}</p>
                            <p><strong>Guests:</strong> ${guests}</p>
                            <p><strong>Message:</strong> ${message || 'No additional notes.'}</p>
                            <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
                            <p style="font-size: 12px; color: #888;">This email was automatically generated by the Falak Hall Management System.</p>
                        </div>
                    `,
                });
            } catch (err) { console.error('Email failed to send:', err); }
        }

        res.status(201).json({ success: true, message: 'Booking received!', data: { id: result.insertedId } });
    } catch (error) {
        console.error('Booking error:', error);
        res.status(500).json({ success: false, message: 'Server error. Please contact us directly.' });
    }
});

app.get('/api/availability', async (req, res) => {
    try {
        const db = await connectDB();
        const dates = await db.collection('availability').find({}).toArray();
        res.json({ success: true, data: dates });
    } catch (error) {
        res.status(500).json({ success: false, message: 'Server error.' });
    }
});

// ── ADMIN API ──────────────────────────────────────────

// Login — checks username AND token (password)
app.post('/api/admin/login', (req, res) => {
    const { username, password } = req.body;
    const validUsername = 'ahmedchoudery1';
    const validToken = process.env.ADMIN_TOKEN;

    if (!username || !password) {
        return res.status(400).json({ success: false, message: 'Username and password required.' });
    }
    if (username !== validUsername || password !== validToken) {
        return res.status(401).json({ success: false, message: 'Invalid username or password.' });
    }
    res.json({ success: true, token: validToken });
});

app.get('/api/admin/bookings', adminAuth, async (req, res) => {
    try {
        const db = await connectDB();
        const filter = {};
        if (req.query.status && req.query.status !== 'all') filter.status = req.query.status;
        const bookings = await db.collection('bookings').find(filter).sort({ createdAt: -1 }).toArray();
        res.json({ success: true, data: bookings });
    } catch (error) { res.status(500).json({ success: false, message: 'Server error.' }); }
});

app.post('/api/admin/bookings', adminAuth, async (req, res) => {
    try {
        const db = await connectDB();
        const { name, phone, email, eventDate, eventType, hall, guests, message, status } = req.body;
        if (!name || !phone || !eventDate || !eventType)
            return res.status(400).json({ success: false, message: 'Name, phone, date, and event type required.' });
        const booking = {
            name, phone,
            email: email || '',
            eventDate, eventType,
            hall: hall || 'Any Available',
            guests: parseInt(guests) || 0,
            message: message || '',
            status: status || 'approved',
            source: 'manual',
            createdAt: new Date(),
        };
        const result = await db.collection('bookings').insertOne(booking);
        
        if (booking.status === 'approved') {
            await db.collection('availability').updateOne(
                { date: eventDate },
                { $set: { date: eventDate, status: 'booked', bookingId: result.insertedId, source: 'manual-booking' } },
                { upsert: true }
            );
        }
        res.status(201).json({ success: true, message: 'Booking added.', bookingId: result.insertedId });
    } catch (error) { res.status(500).json({ success: false, message: 'Server error.' }); }
});

app.put('/api/admin/bookings/:id', adminAuth, async (req, res) => {
    try {
        const db = await connectDB();
        const { id } = req.params;
        if (!ObjectId.isValid(id)) return res.status(400).json({ success: false, message: 'Invalid ID.' });
        const { name, phone, email, eventDate, eventType, hall, guests, message, status } = req.body;
        const updateData = { updatedAt: new Date() };
        if (name) updateData.name = name;
        if (phone) updateData.phone = phone;
        if (email !== undefined) updateData.email = email;
        if (eventDate) updateData.eventDate = eventDate;
        if (eventType) updateData.eventType = eventType;
        if (hall) updateData.hall = hall;
        if (guests !== undefined) updateData.guests = parseInt(guests) || 0;
        if (message !== undefined) updateData.message = message;
        const oldBooking = await db.collection('bookings').findOne({ _id: new ObjectId(id) });
        if (!oldBooking) return res.status(404).json({ success: false, message: 'Booking not found.' });

        const result = await db.collection('bookings').updateOne(
            { _id: new ObjectId(id) }, { $set: updateData }
        );

        // ── Availability Sync Logic ──
        const currentBooking = { ...oldBooking, ...updateData };
        
        // 1. If date changed and old was approved, free the OLD date
        if (oldBooking.status === 'approved' && oldBooking.eventDate !== currentBooking.eventDate) {
            await db.collection('availability').deleteOne({ date: oldBooking.eventDate });
        }

        // 2. Sync availability based on CURRENT status
        if (currentBooking.status === 'approved') {
            await db.collection('availability').updateOne(
                { date: currentBooking.eventDate },
                { $set: { date: currentBooking.eventDate, status: 'booked', bookingId: new ObjectId(id) } },
                { upsert: true }
            );
        } else {
            // If NOT approved (pending/rejected/cancelled), ensure the date is FREE (unless other approved booking exists)
            // For now, assume 1 booking per date.
            await db.collection('availability').deleteOne({ date: currentBooking.eventDate });
        }
        res.json({ success: true, message: 'Booking updated.' });
    } catch (error) { console.error(error); res.status(500).json({ success: false, message: 'Server error.' }); }
});

app.delete('/api/admin/bookings/:id', adminAuth, async (req, res) => {
    try {
        const db = await connectDB();
        const { id } = req.params;
        if (!ObjectId.isValid(id)) return res.status(400).json({ success: false, message: 'Invalid ID.' });
        const booking = await db.collection('bookings').findOne({ _id: new ObjectId(id) });
        const result = await db.collection('bookings').deleteOne({ _id: new ObjectId(id) });
        if (result.deletedCount === 0)
            return res.status(404).json({ success: false, message: 'Booking not found.' });
        if (booking?.eventDate) await db.collection('availability').deleteOne({ date: booking.eventDate });
        res.json({ success: true, message: 'Booking deleted.' });
    } catch (error) { res.status(500).json({ success: false, message: 'Server error.' }); }
});

app.get('/api/admin/availability', adminAuth, async (req, res) => {
    try {
        const db = await connectDB();
        const dates = await db.collection('availability').find({}).sort({ date: 1 }).toArray();
        res.json({ success: true, data: dates });
    } catch (error) { res.status(500).json({ success: false, message: 'Server error.' }); }
});

app.post('/api/admin/availability', adminAuth, async (req, res) => {
    try {
        const db = await connectDB();
        const { date, status } = req.body;
        if (!date || !status)
            return res.status(400).json({ success: false, message: 'Date and status required.' });
        if (status === 'available') {
            await db.collection('availability').deleteOne({ date });
        } else {
            await db.collection('availability').updateOne(
                { date },
                { $set: { date, status: 'booked', source: 'manual-block' } },
                { upsert: true }
            );
        }
        res.json({ success: true, message: `Date marked as ${status}.` });
    } catch (error) { res.status(500).json({ success: false, message: 'Server error.' }); }
});

// SPA fallback — disable caching and ETags for index.html to force 200 OK
app.get('*', (req, res) => {
    res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, proxy-revalidate');
    res.setHeader('Pragma', 'no-cache');
    res.setHeader('Expires', '0');
    res.setHeader('Surrogate-Control', 'no-store');
    res.sendFile(path.resolve(process.cwd(), 'dist', 'index.html'), { etag: false, lastModified: false });
});

if (process.env.NODE_ENV !== 'production') {
    app.listen(PORT, async () => {
        console.log(`🏛️  Falak Hall server → http://localhost:${PORT}`);
        try { await connectDB(); } catch (e) { console.error('DB failed:', e.message); }
    });
}

export default app;